name: AWS S3 workflow
on:
  push
env:
  BUCKET_NAME : "githubexpeirmet"
  AWS_REGION : "ap-south-1"
permissions:
  id-token: write  
  contents: read   
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
    #  - name: Set up Node.js
    #    uses: actions/setup-node@v3
    #    with:
     #     node-version: '16' # Replace with the Node.js version used in your project

 #     - name: Install dependencies
     #   run: npm install

    # - name: Build the project
     #   run: npm run build
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:cloudfront::850995565642:distribution/EYT082JCVY0CO
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Sync s3 bucket
        run: |
          aws s3 sync . s3://${{ env.BUCKET_NAME }}
          aws cloudfront create-invalidation --distribution-id EYT082JCVY0CO --paths '/*' 
